#!/usr/bin/env bash
#!nstall_load_balancere/usr/bin/env bash
# Installs HAProxy version 2.0 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor

frontend www-http
    bind   0.0.0.0:80
    reqadd X-Forwarded-Proto:\ http
    default_backend www-backend
frontend www-https
    bind   0.0.0.0:443 ssl crt /etc/haproxy/certs/www.anten.tech.pem
    reqadd X-Forwarded-Proto:\ https
    acl    letsencrypt-acl path_beg /.well-known/acme-challenge/
    use_backend letsencrypt-backend if letsencrypt-acl
    default_backend www-backend
backend www-backend
    balance  roundrobin
    redirect scheme https if !{ ssl_fc }
    server 1701-web-01 35.237.92.54:80 check
    server 1701-web-02 3.238.90.226:80 check

" >> /etc/haproxy/haproxy.cfg

service haproxy start
